### ISSUE TITLE
npm run prod - Unexpected token <

### ISSUE THREAD

**Issue by wrannaman** [nightwolfz/mobx-starter#35]
I saw this issue closed previously, but am experiencing it again. 

`node -v  = v8.5.0`
`npm -v = 5.3.0 `
if you clone a fresh build of this repo and do `npm i && npm run prod` the build will not fail ( or indicate there was a compilation error however the browser doesn't have any css :( I'm still looking into why this is failing with a `Uncaught SyntaxError: Unexpected token <` in the browser console upon load, but any insight would be appreciated. 

Thanks!

**Comment by edongashi** [comment]
I've had this issue. It happens because a request to localhost/build/bundle.css does not get picked up by koa static middleware, instead it passes as a regular route. In the app there's no route that matches that path so the 404 view is returned. The unexpected `<`  is the beginning of the returned html.

I've changed a lot of stuff so I can't tell you exactly how to fix it. But you should check around server/config.js and the mounting of koa static inside the server initialization.

**Comment by wrannaman** [comment]
Ah that makes sense, I've got it working now by mounting the build directory. Looks like the code in the /server/config.js is commented out. 
`static: {`
`      //'/build': root('build'),`
`      '/assets': root('src/assets')`
`}`

As is usually the case it looks like I have a separate issue with the prod build and UglifyJs...  Thanks so much for your help. I appreciate it!
