### ISSUE TITLE
externals?

### ISSUE THREAD

**Issue by mikecann** [nightwolfz/mobx-starter#9]
Hey,

I would like to get that 500kb prod-bundle down a little. Im thinking externalizing React and Lodash etc, how would I go about that you think?

Mike

**Comment by nightwolfz** [comment]
You might consider using underscore instead of lodash for its smaller filesize.

Enabling gzip on your server should give you a BIG reduction in filesize as well.

Or just wait until they fix treeshaking in webpack 2 ;-)

For externalizing, maybe use the libraries hosted on a CDN ? Generally I don't externalize anything but if you need to, you'll have to find a way for webpack to exclude them from the bundle.

**Comment by nightwolfz** [comment]
If you are really serious about bundle size, you might want to use [InfernoJS](https://github.com/trueadm/inferno) instead of React at the cost of some nice components available out there made just for React.

There's a starter-kit for that as well:  [inferno-starter](https://github.com/nightwolfz/inferno-starter)

**Comment by mikecann** [comment]
Oh okay cool, how come you dont externalize anything? Every time you update your client code that will cause the whole bundle to be invalidated and thus re-downloaded?

Thanks for that info on inferno, really good to know, and it looks like you enjoy making these starters!

**Comment by nightwolfz** [comment]
My whole bundle is around 60kb gzipped (inferno+mobx+all size optimized custom components), so it's not really a problem for me. Images however, now that's heavy.

**Comment by mikecann** [comment]
Wow, much smaller, thanks.
